spring:
  application:
    name: index-data-service
  redis:
    host: 39.107.85.253
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/